apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rag-chatbot
resources:
- namespace.yaml
- configmap.yaml
- api-deployment.yaml
- worker-deployment.yaml
- api-pdb.yaml
- worker-pdb.yaml
- api-hpa.yaml
- worker-hpa.yaml
- service.yaml
