"use strict";
const state = {token: "", conversation: null, pending: null, busy: false};
const $ = id => document.getElementById(id);
function el(tag, text, css) { const n=document.createElement(tag); if(text!==undefined)n.textContent=text; if(css)n.className=css; return n; }
function notice(text,bad=false){$("notice").textContent=text;$("notice").className=bad?"error":"ok";}
async function api(path,options={}){
  if(!state.token)throw new Error("Paste a bearer token and connect first.");
  const headers=new Headers(options.headers||{});headers.set("Authorization",`Bearer ${state.token}`);
  if(options.body && !(options.body instanceof FormData))headers.set("Content-Type","application/json");
  const response=await fetch(path,{...options,headers});const data=await response.json();
  if(!response.ok){const e=new Error(data.error?.message||`Request failed (${response.status})`);e.code=data.error?.code;throw e;}
  return data;
}
function button(text,action){const n=el("button",text,"secondary");n.type="button";n.addEventListener("click",async()=>{n.disabled=true;try{await action();}catch(e){notice(e.message,true);}finally{n.disabled=false;}});return n;}
async function refresh(){const data=await api("/v1/documents");$("documents").replaceChildren();
  if(!data.documents.length)$("documents").append(el("p","No documents yet."));
  for(const doc of data.documents){const box=el("div",undefined,"item");box.append(el("strong",doc.title),el("div",`${doc.state} · ${doc.visibility}${doc.is_learning?" · reviewed correction":""}`,"meta"));
    if(doc.error_code)box.append(el("p",doc.error_code,"error"));const actions=el("div",undefined,"actions");
    actions.append(button("Inspect chunks",async()=>{const result=await api(`/v1/documents/${doc.id}/chunks`);const details=el("details");details.open=true;details.append(el("summary","Source chunks"));for(const chunk of result.chunks)details.append(el("pre",`Chunk ID: ${chunk.id}\n${chunk.content}`));box.append(details);}));
    if(doc.state==="failed")actions.append(button("Retry",async()=>{await api(`/v1/documents/${doc.id}/retry`,{method:"POST"});await refresh();}));
    actions.append(button("Delete",async()=>{if(confirm("Delete this source and revoke corrections that depend on it?")){await api(`/v1/documents/${doc.id}`,{method:"DELETE"});await refresh();}}));box.append(actions);$("documents").append(box);
  }
}
$("connect").addEventListener("submit",async e=>{e.preventDefault();if(state.busy)return;state.token=$("token").value.trim().replace(/^Bearer\s+/i,"");state.conversation=null;state.pending=null;$("messages").replaceChildren();$("proposals").replaceChildren();try{await refresh();notice("Connected. Upload a document or ask a question.");}catch(e){notice(e.message,true);}});
$("refresh").addEventListener("click",()=>refresh().catch(e=>notice(e.message,true)));
$("upload").addEventListener("submit",async e=>{e.preventDefault();const send=e.submitter;send.disabled=true;try{const file=$("file").files[0];if(file){const body=new FormData();body.set("file",file);body.set("visibility",$("visibility").value);await api("/v1/documents/upload",{method:"POST",body});}else{await api("/v1/documents",{method:"POST",body:JSON.stringify({title:$("title").value,text:$("text").value,visibility:$("visibility").value})});}notice("Queued for indexing. Refresh to check its status.");await refresh();}catch(e){notice(e.message,true);}finally{send.disabled=false;}});
function feedback(box,answer){const actions=el("div",undefined,"actions");actions.append(button("Helpful",async()=>{await api("/v1/feedback",{method:"POST",body:JSON.stringify({answer_id:answer.answer_id,rating:1})});notice("Feedback recorded.");}));
  actions.append(button("Suggest correction",async()=>{const form=el("form");const text=el("textarea");text.maxLength=3000;text.required=true;text.placeholder="Write the corrected answer.";const label=el("label",undefined,"check");const consent=el("input");consent.type="checkbox";label.append(consent,document.createTextNode("Allow an administrator to review this question and correction for learning"));const scope=el("select");for(const [value,name]of[["private","Learn only for me"],["tenant","Allow learning for my tenant"]]){const option=el("option",name);option.value=value;scope.append(option);}const submit=el("button","Submit correction");form.append(text,label,scope,submit);box.append(form);
    form.addEventListener("submit",async e=>{e.preventDefault();submit.disabled=true;try{const result=await api("/v1/feedback",{method:"POST",body:JSON.stringify({answer_id:answer.answer_id,rating:-1,correction:text.value,consent_to_learning:consent.checked,learning_scope:scope.value})});notice(`Correction ${result.state}. It has not been automatically indexed.`);form.replaceChildren(el("p",`Feedback ID: ${result.id}`),button("Withdraw learning consent",async()=>{await api(`/v1/feedback/${result.id}/withdraw`,{method:"POST"});notice("Consent withdrawn; any learned document has been revoked.");}));}catch(e){notice(e.message,true);submit.disabled=false;}});
  }));box.append(actions);
}
function showAnswer(data){const box=el("article",undefined,"message");box.append(el("div",data.answer,"answer"),el("div",`${data.status} · ${data.demo_mode?"extractive demo":"live model"} · ${data.agent_steps.join(" → ")}`,"meta"));for(const source of data.sources){const details=el("details");details.append(el("summary",`[${source.number}] ${source.title}`),el("blockquote",source.quote),el("pre",`Chunk ID: ${source.chunk_id}`));if(/^https?:\/\//i.test(source.source_uri)){const a=el("a","Open source");a.href=source.source_uri;a.target="_blank";a.rel="noopener noreferrer";details.append(a);}box.append(details);}feedback(box,data);$("messages").append(box);box.scrollIntoView({block:"nearest"});}
$("chat").addEventListener("submit",async e=>{e.preventDefault();if(state.busy)return;const message=$("question").value.trim();if(!message)return;const payload={message,conversation_id:state.conversation};const signature=JSON.stringify(payload);if(!state.pending||state.pending.signature!==signature)state.pending={signature,payload,key:crypto.randomUUID(),displayed:false};const pending=state.pending;if(!pending.displayed){$("messages").querySelector(".empty")?.remove();$("messages").append(el("div",message,"message question"));pending.displayed=true;}state.busy=true;$("send").disabled=true;$("progress").textContent="Retrieving sources and verifying the answer…";try{const data=await api("/v1/chat",{method:"POST",headers:{"Idempotency-Key":pending.key},body:JSON.stringify(pending.payload)});state.conversation=data.conversation_id;state.pending=null;$("question").value="";showAnswer(data);$("progress").textContent="";}catch(e){if(e.code==="stale_answer")state.pending=null;notice(e.message,true);$("progress").textContent="Press Ask again to retry safely.";}finally{state.busy=false;$("send").disabled=false;}});
$("new-chat").addEventListener("click",()=>{if(state.busy)return;state.conversation=null;state.pending=null;$("messages").replaceChildren();$("progress").textContent="New conversation.";});
async function reviews(){const data=await api("/v1/learning/proposals");$("proposals").replaceChildren();for(const p of data.proposals){const box=el("div",undefined,"item");box.append(el("strong",`${p.state} · ${p.scope}`),el("p",p.question),el("blockquote",p.correction));if(p.state==="pending"){const chunk=el("input");chunk.placeholder="Shared original source chunk ID";const quote=el("textarea");quote.placeholder="Exact supporting quote";const reason=el("input");reason.placeholder="Review reason";const actions=el("div",undefined,"actions");for(const action of["approve","reject"])actions.append(button(action,async()=>{await api(`/v1/learning/proposals/${p.id}/review`,{method:"POST",body:JSON.stringify({action,reason:reason.value,evidence:action==="approve"?[{chunk_id:chunk.value.trim(),quote:quote.value.trim()}]:[]})});notice(`Review recorded: ${action}. Approved corrections still need indexing.`);await reviews();}));box.append(chunk,quote,reason,actions);}else if(["approved","published"].includes(p.state)){box.append(button("Revoke correction",async()=>{await api(`/v1/learning/proposals/${p.id}/revoke`,{method:"POST"});await reviews();}));}$("proposals").append(box);}if(!data.proposals.length)$("proposals").append(el("p","No consented learning proposals."));}
$("reviews").addEventListener("click",()=>reviews().catch(e=>notice(e.message,true)));
fetch("/health/ready").then(r=>r.json()).then(data=>{$("mode").textContent=data.status!=="ready"?"Service not ready":data.demo_mode?"MOCK MODE · extractive demo, not an LLM":"LIVE MODEL · evidence-checked answers";}).catch(()=>{$("mode").textContent="Service unreachable";});
